### ISSUE TITLE
Maintenance state?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/widget-cookiecutter#55]
I see quite a few issues which are trivial, but 1-2 years old. For example there is no license, https://github.com/jupyter-widgets/widget-cookiecutter/issues/25, etc. Looking at the PRs gives me a similar impression. Is this project still actively maintained, or is there some alternative?

**Comment by vidartf** [comment]
A slightly more maintained version is the typescript version here: https://github.com/jupyter-widgets/widget-ts-cookiecutter. I also have a personal one that I use whenever I make a widget project for myself (https://github.com/jupyter-widgets/widget-ts-cookiecutter). I use that since I have some personal preferences for which tech to use / how to organize the widget package that might not make sense to first-time users.

The maintenance model here is basically to fix it when you find an issue while using it (PR ideally). This should help with the learning experience, although it is a bit of a baptism by fire..
